# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'accounta-bill-a-buddy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for accounta-bill-a-buddy
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
#  pod 'Firebase/Core'

end
